# Generated by Django 4.2.2 on 2023-06-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wesite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=150)),
                ('website_url', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=100)),
                ('app_pass', models.CharField(max_length=200)),
            ],
        ),
    ]
