# Generated by Django 4.2.2 on 2023-06-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wesite',
            name='website_url',
            field=models.URLField(max_length=250),
        ),
    ]
