# Generated by Django 4.2.2 on 2023-06-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleKeywordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('article', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Keyword',
            new_name='BulkKeywordModel',
        ),
    ]
