# Generated by Django 4.2.2 on 2023-06-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_singlekeywordmodel_rename_keyword_bulkkeywordmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenaiAPIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('API_Key', models.CharField(max_length=500)),
            ],
        ),
    ]
