# Generated by Django 4.2.2 on 2023-06-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_openaiapimodel_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiapimodel',
            name='engine',
            field=models.CharField(max_length=150),
        ),
    ]
