# Generated by Django 4.2.2 on 2023-06-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_openaiapimodel_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiapimodel',
            name='engine',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
