# Generated by Django 4.2.2 on 2023-06-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_openaiapimodel_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiapimodel',
            name='engine',
            field=models.CharField(default='text-davinci-003', max_length=150),
        ),
    ]
