# Generated by Django 4.2.2 on 2023-06-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_openaiapimodel_engine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkkeywordmodel',
            name='article',
        ),
        migrations.AddField(
            model_name='bulkkeywordmodel',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
