# Generated by Django 4.2.2 on 2023-06-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_bulkkeywordmodel_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singlekeywordmodel',
            old_name='article',
            new_name='outline',
        ),
        migrations.AddField(
            model_name='singlekeywordmodel',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
