# Generated by Django 4.2.3 on 2023-07-07 12:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_article_singlekeywordmodel_outline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkkeywordmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singlekeywordmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
